FROM debian 
RUN apt-get update
RUN apt-get upgrade -y
RUN apt-get install -y iceweasel
RUN apt-get install -y libcanberra-gtk-module libcanberra-gtk3-module 
RUN apt-get install -y gtk2-engines-pixbuf
RUN apt-get clean
COPY theme /usr/share/themes/Adwaita
COPY config/vendor.js /usr/lib/iceweasel/browser/defaults/preferences/vendor.js
RUN adduser iceweasel
ENV HOME /home/iceweasel 
COPY profil /home/iceweasel/.mozilla/firefox
COPY config/gtk.conf /home/iceweasel/.config/gtk-3.0/settings.ini
RUN chown iceweasel:users -R /home/iceweasel/
USER iceweasel
CMD []
ENTRYPOINT ["/usr/bin/iceweasel"]
