FROM ubuntu 
RUN apt-get update && apt-get install -y chromium-browser && apt-get clean

RUN useradd -ms /bin/bash chromium
USER chromium
ENV HOME /home/chromium 
CMD []
ENTRYPOINT ["/usr/bin/chromium-browser", "--no-sandbox"]
