# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1453298974);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1453299094);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("beacon.enabled", false);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 1);
user_pref("browser.customizemode.tip0.shown", true);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 34);
user_pref("browser.newtabpage.enabled", false);
user_pref("browser.newtabpage.enhanced", false);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1457603644610");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1457607244610");
user_pref("browser.search.countryCode", "IT");
user_pref("browser.search.defaultenginename", "DuckDuckGo");
user_pref("browser.search.region", "IT");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20160209234642");
user_pref("browser.startup.homepage", "https://duckduckgo.com");
user_pref("browser.startup.homepage_override.buildID", "20160209234642");
user_pref("browser.startup.homepage_override.mstone", "44.0.2");
user_pref("browser.syncPromoViewsLeftMap", "{\"addons\":4}");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"PanelUI-contents\":[\"privatebrowsing-button\",\"history-panelmenu\",\"preferences-button\",\"add-ons-button\",\"developer-button\"],\"addon-bar\":[\"addonbar-closebutton\",\"status-bar\"],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"urlbar-container\",\"downloads-button\",\"home-button\",\"loop-button\",\"ublock0-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"ublock0-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\",\"PanelUI-contents\"],\"currentVersion\":4,\"newElementCount\":0}");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1453298854315");
user_pref("datareporting.healthreport.pendingDeleteRemoteData", true);
user_pref("datareporting.policy.firstRunTime", "1453298853904");
user_pref("datareporting.sessions.current.activeTicks", 1);
user_pref("datareporting.sessions.current.firstPaint", 706);
user_pref("datareporting.sessions.current.main", 130);
user_pref("datareporting.sessions.current.sessionRestored", 4203);
user_pref("datareporting.sessions.current.startTime", "1457603635268");
user_pref("datareporting.sessions.current.totalTime", 12);
user_pref("datareporting.sessions.currentIndex", 1);
user_pref("datareporting.sessions.previous.0", "{\"s\":1453298853557,\"a\":30,\"t\":291,\"c\":true,\"m\":50,\"fp\":2617,\"sr\":3075}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("dom.apps.reset-permissions", true);
user_pref("dom.mozApps.used", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.bootstrappedAddons", "{\"uBlock0@raymondhill.net\":{\"version\":\"1.5.5\",\"type\":\"extension\",\"descriptor\":\"/home/firefox/.mozilla/firefox/9ihzjopn.default/extensions/uBlock0@raymondhill.net.xpi\",\"multiprocessCompatible\":true,\"runInSafeMode\":false}}");
user_pref("extensions.databaseSchema", 17);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.2,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:44.0.2");
user_pref("extensions.getAddons.cache.lastUpdate", 1457603638);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppVersion", "44.0.2");
user_pref("extensions.lastPlatformVersion", "44.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ublock0.cloudStorage.myFiltersPane", "");
user_pref("extensions.ublock0.cloudStorage.myRulesPane", "");
user_pref("extensions.ublock0.cloudStorage.tpFiltersPane", "");
user_pref("extensions.ublock0.cloudStorage.whitelistPane", "");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.experiment.hidden", true);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.xpiState", "{\"app-profile\":{\"uBlock0@raymondhill.net\":{\"d\":\"/home/firefox/.mozilla/firefox/9ihzjopn.default/extensions/uBlock0@raymondhill.net.xpi\",\"e\":true,\"v\":\"1.5.5\",\"st\":1456845145000}},\"app-global\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"44.0.2\",\"st\":1457529966000,\"mt\":1455064035000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com.xpi\",\"e\":true,\"v\":\"3.2\",\"st\":1442597111000}}}");
user_pref("gecko.buildID", "20160209234642");
user_pref("gecko.mstone", "44.0.2");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1453298926);
user_pref("media.gmp-gmpopenh264.version", "1.5.3");
user_pref("media.gmp-manager.buildID", "20160106234723");
user_pref("media.gmp-manager.lastCheck", 1453298919);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.migrateClearSavedPwdsOnExit", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.myFiltersPane", true);
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.myRulesPane", true);
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.tpFiltersPane", true);
user_pref("services.sync.prefs.sync.extensions.ublock0.cloudStorage.whitelistPane", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1457603635);
user_pref("toolkit.telemetry.cachedClientID", "742e1851-38c6-402d-8093-cb4de0df79d9");
user_pref("toolkit.telemetry.previousBuildID", "20160209234642");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
